name       : faba-icon-theme
version    : 4.1.2
release    : 8
source     :
    - https://github.com/snwh/faba-icon-theme/archive/v4.1.2.tar.gz : c7af0409846af799e15910257021a9c898167f4fddec6161b4ceab230c6d2242
license    : CC-BY-SA-4.0
summary    : Faba Icon Theme
component  : desktop.theme
description: |
    Faba is a Linux desktop icon theme. It has designed with simplicity and compliance to standards in mind. Faba's purpose is to serve as a base icon theme to others (such as Moka). It comprises only of a system icons –folders, mimetypes, toolbar icons, etc.
setup      : |
    %patch -p1 < $pkgfiles/e50649d0171fd8cce42404c7c5002d77710ffcfc.patch
    chmod +x autogen.sh
    %autogen
build      : |
    %make
install    : |
    %make_install
