name       : faba-icon-theme
version    : 4.0
release    : 6
source     :
    - https://solus-project.com/sources/faba-icon-theme-4.0.tar.xz : a622440cc9494656459366830c5da6f9dc4f9c1619882ea478e35410246fd1dc
license    : CC-BY-SA-4.0
summary    : Faba Icon Theme
rundeps    :
    - moka-icon-theme
description: |
    Faba is a Linux desktop icon theme. It has designed with simplicity and compliance to standards in mind. Faba's purpose is to serve as a base icon theme to others (such as Moka). It comprises only of a system icons –folders, mimetypes, toolbar icons, etc.
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mkdir -p %installroot%/usr/share/doc/faba-icon-theme/
    cp -Rv Faba %installroot%/usr/share/icons/
    chmod -R a+r %installroot%/usr/share/icons/Faba
    install -D -m 00644 COPYING %installroot%/usr/share/doc/faba-icon-theme/COPYING
