name       : faba-icon-theme
version    : '4.3'
release    : 10
source     :
    - https://github.com/snwh/faba-icon-theme/archive/v4.3.tar.gz : c87ce7dae8df6b25228297baa1be96cfad06c5c109ff60fedf1f0343bb0196a2
license    : CC-BY-SA-4.0
summary    : Faba Icon Theme
component  : desktop.theme
description: |
    Faba is a Linux desktop icon theme. It has designed with simplicity and compliance to standards in mind. Faba's purpose is to serve as a base icon theme to others (such as Moka). It comprises only of a system icons –folders, mimetypes, toolbar icons, etc.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
