name       : faba-icon-theme
version    : 4.0
release    : 4
source     :
    - https://github.com/moka-project/faba-icon-theme/raw/master/faba-icon-theme-4.0.tar.gz : 0bde2c0ee63f2881bb72c927145504bbabd6ecbaf5c43ae2bf1e2dffa2f0a67c
license    : GPL-2.0
summary    : Faba Icon Theme
description: |
    Faba is a Linux desktop icon theme. It has designed with simplicity and compliance to standards in mind. Faba's purpose is to serve as a base icon theme to others (such as Moka). It comprises only of a system icons –folders, mimetypes, toolbar icons, etc.
builddeps  :
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/icons/
    mkdir -p %installroot%/usr/share/doc/faba-icon-theme/
    mv Faba %installroot%/usr/share/icons/
    mv * %installroot%/usr/share/doc/faba-icon-theme/
    chmod a+r %installroot%/usr/share/icons/Faba
